spring.application.name=backend
server.address=0.0.0.0
server.port=9091

spring.profiles.active=prod

spring.mvc.hiddenmethod.filter.enabled=true

spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=587
spring.mail.username=univibe2025@yahoo.com
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8